namespace FreeGLBA;

// ============================================================================
// FREEGLBA PROJECT - IDataAccess Extension
// Interface method signatures for generated entities
// Generated by Entity Builder Wizard
// ============================================================================

public partial interface IDataAccess
{
    // API Request Logging methods
    Task<Guid> CreateApiLogAsync(EFModels.EFModels.ApiRequestLogItem log);

    Task<bool> DeleteAccessEventAsync(Guid id);
    Task<bool> DeleteComplianceReportAsync(Guid id);
    Task<bool> DeleteDataSubjectAsync(Guid id);
    Task<bool> DeleteSourceSystemAsync(Guid id);
    Task<bool> DisableBodyLoggingAsync(Guid configId);
    Task<DataObjects.BodyLoggingConfig> EnableBodyLoggingAsync(Guid sourceSystemId, Guid enabledByUserId, string enabledByUserName, int durationHours, string reason);
    Task<DataObjects.AccessEvent?> GetAccessEventAsync(Guid id);
    Task<List<DataObjects.AccessEventLookup>> GetAccessEventLookupsAsync();

    // AccessEvent methods
    Task<DataObjects.AccessEventFilterResult> GetAccessEventsAsync(DataObjects.AccessEventFilter filter);
    Task<DataObjects.ApiRequestLog?> GetApiLogAsync(Guid id);
    Task<DataObjects.ApiLogDashboardStats> GetApiLogDashboardStatsAsync(DateTime from, DateTime to);
    Task<DataObjects.ApiLogFilterResult> GetApiLogsAsync(DataObjects.ApiLogFilter filter);

    // Body Logging Configuration methods
    Task<EFModels.EFModels.BodyLoggingConfigItem?> GetBodyLoggingConfigAsync(Guid sourceSystemId);
    Task<List<DataObjects.BodyLoggingConfig>> GetBodyLoggingConfigsAsync();
    Task<DataObjects.ComplianceReport?> GetComplianceReportAsync(Guid id);
    Task<List<DataObjects.ComplianceReportLookup>> GetComplianceReportLookupsAsync();

    // ComplianceReport methods
    Task<DataObjects.ComplianceReportFilterResult> GetComplianceReportsAsync(DataObjects.ComplianceReportFilter filter);
    Task<DataObjects.DataSubject?> GetDataSubjectAsync(Guid id);
    Task<List<DataObjects.DataSubjectLookup>> GetDataSubjectLookupsAsync();

    // DataSubject methods
    Task<DataObjects.DataSubjectFilterResult> GetDataSubjectsAsync(DataObjects.DataSubjectFilter filter);
    Task<DataObjects.SourceSystem?> GetSourceSystemAsync(Guid id);
    Task<List<DataObjects.SourceSystemLookup>> GetSourceSystemLookupsAsync();
    // SourceSystem methods
    Task<DataObjects.SourceSystemFilterResult> GetSourceSystemsAsync(DataObjects.SourceSystemFilter filter);
    Task<DataObjects.AccessEvent?> SaveAccessEventAsync(DataObjects.AccessEvent dto);

    /// <summary>
    /// Saves many new AccessEvents in a single round trip, then updates
    /// SourceSystem and DataSubject statistics in aggregate.
    /// </summary>
    Task<DataObjects.AccessEventBulkResult> SaveAccessEventsAsync(List<DataObjects.AccessEvent> items);
    Task<DataObjects.ComplianceReport?> SaveComplianceReportAsync(DataObjects.ComplianceReport dto);
    Task<DataObjects.DataSubject?> SaveDataSubjectAsync(DataObjects.DataSubject dto);
    Task<DataObjects.SourceSystem?> SaveSourceSystemAsync(DataObjects.SourceSystem dto);
}
