namespace FreeGLBA;

#region FreeGLBA DataObjects
// ============================================================================
// FREEGLBA PROJECT - Generated by Entity Builder Wizard
// Entities: SourceSystem, AccessEvent, DataSubject, ComplianceReport
// Relationships: 1
// ============================================================================

public partial class DataObjects
{
    /// <summary>SourceSystem data transfer object.</summary>
    public class SourceSystem
    {
        /// <summary>Hashed API key (stored in database)</summary>
        public string ApiKey { get; set; } = string.Empty;
        public string ContactEmail { get; set; } = string.Empty;
        public string DisplayName { get; set; } = string.Empty;
        public long EventCount { get; set; } = 0;
        public bool IsActive { get; set; } = true;
        public DateTime? LastEventReceivedAt { get; set; }
        public string Name { get; set; } = string.Empty;
        /// <summary>Plaintext API key - only populated when newly generated. Show to user ONCE then discard.</summary>
        public string? NewApiKey { get; set; }
        /// <summary>Primary key</summary>
        public Guid SourceSystemId { get; set; }
    }

    /// <summary>Filter criteria for SourceSystemQueries.</summary>
    public class SourceSystemFilter
    {
        public bool? IsActiveFilter { get; set; }
        public DateTime? LastActivityAfter { get; set; }
        public DateTime? LastActivityBefore { get; set; }
        public long? MaxEventCount { get; set; }
        // Advanced filters
        public long? MinEventCount { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 25;
        public string? Search { get; set; }
        public int Skip => (Page - 1) * PageSize;
        public string SortColumn { get; set; } = "SourceSystemId";
        public bool SortDescending { get; set; } = true;
    }

    /// <summary>Paginated result for SourceSystem queries.</summary>
    public class SourceSystemFilterResult
    {
        public int Page { get; set; }
        public int PageSize { get; set; }
        public List<SourceSystem> Records { get; set; } = new();
        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);
        public int TotalRecords { get; set; }
    }


    /// <summary>AccessEvent data transfer object.</summary>
    public class AccessEvent
    {
        public DateTime AccessedAt { get; set; }
        /// <summary>Primary key</summary>
        public Guid AccessEventId { get; set; }
        public string AccessType { get; set; } = string.Empty;
        /// <summary>JSON for flexible extras</summary>
        public string AdditionalData { get; set; } = string.Empty;
        /// <summary>When the user acknowledged the privacy agreement.</summary>
        public DateTime? AgreementAcknowledgedAt { get; set; }
        /// <summary>Copy of the privacy notice/agreement text shown to user at time of access.</summary>
        public string AgreementText { get; set; } = string.Empty;
        public string DataCategory { get; set; } = string.Empty;
        public string IpAddress { get; set; } = string.Empty;
        public string Purpose { get; set; } = string.Empty;
        public DateTime ReceivedAt { get; set; }
        /// <summary>Dedupe key from source</summary>
        public string SourceEventId { get; set; } = string.Empty;
        public Guid SourceSystemId { get; set; }
        /// <summary>Display name for related SourceSystem.</summary>
        public string SourceSystemName { get; set; } = string.Empty;
        /// <summary>Count of subjects accessed. 1 for single, N for bulk exports.</summary>
        public int SubjectCount { get; set; } = 1;
        /// <summary>Primary subject ID (for single-subject access) or "BULK" for multi-subject.</summary>
        public string SubjectId { get; set; } = string.Empty;
        /// <summary>JSON array of all subject IDs for bulk access (e.g., CSV exports).</summary>
        public string SubjectIds { get; set; } = string.Empty;
        public string SubjectType { get; set; } = string.Empty;
        public string UserDepartment { get; set; } = string.Empty;
        public string UserEmail { get; set; } = string.Empty;
        public string UserId { get; set; } = string.Empty;
        public string UserName { get; set; } = string.Empty;
    }

    /// <summary>Filter criteria for AccessEvent queries.</summary>
    public class AccessEventFilter
    {
        // Advanced filters (friendly property names)
        public DateTime? AccessedAfter { get; set; }
        public (DateTime? Start, DateTime? End)? AccessedAtFilter { get; set; }
        public DateTime? AccessedBefore { get; set; }
        public string? AccessTypeFilter { get; set; }
        public string? DataCategoryFilter { get; set; }
        public string? DepartmentFilter { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 25;
        public (DateTime? Start, DateTime? End)? ReceivedAtFilter { get; set; }
        public string? Search { get; set; }
        public int Skip => (Page - 1) * PageSize;
        public string SortColumn { get; set; } = "AccessEventId";
        public bool SortDescending { get; set; } = true;
        public Guid SourceSystemIdFilter { get; set; }
        public string? SubjectIdFilter { get; set; }
        public string? UserIdFilter { get; set; }
    }

    /// <summary>Paginated result for AccessEvent queries.</summary>
    public class AccessEventFilterResult
    {
        public int Page { get; set; }
        public int PageSize { get; set; }
        public List<AccessEvent> Records { get; set; } = new();
        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);
        public int TotalRecords { get; set; }
    }

    /// <summary>Result of a bulk AccessEvent insert.</summary>
    public class AccessEventBulkResult
    {
        /// <summary>Populated when Success is false.</summary>
        public string Message { get; set; } = string.Empty;
        /// <summary>Number of events written.</summary>
        public int Saved { get; set; }

        /// <summary>Number of distinct data subjects created or updated.</summary>
        public int SubjectsAffected { get; set; }

        /// <summary>True when the whole batch was written successfully.</summary>
        public bool Success { get; set; }
    }


    /// <summary>DataSubject data transfer object.</summary>
    public class DataSubject
    {
        /// <summary>Primary key</summary>
        public Guid DataSubjectId { get; set; }
        public string ExternalId { get; set; } = string.Empty;
        public DateTime FirstAccessedAt { get; set; }
        public DateTime LastAccessedAt { get; set; }
        public string SubjectType { get; set; } = string.Empty;
        public long TotalAccessCount { get; set; } = 0;
        public int UniqueAccessorCount { get; set; } = 0;
    }

    /// <summary>Filter criteria for DataSubject queries.</summary>
    public class DataSubjectFilter
    {
        public DateTime? FirstAccessAfter { get; set; }
        public DateTime? FirstAccessBefore { get; set; }
        public (DateTime? Start, DateTime? End)? FirstAccessedAtFilter { get; set; }
        public DateTime? LastAccessAfter { get; set; }
        public DateTime? LastAccessBefore { get; set; }
        public (DateTime? Start, DateTime? End)? LastAccessedAtFilter { get; set; }
        public long? MaxTotalAccesses { get; set; }
        public int? MaxUniqueAccessors { get; set; }
        public long? MinTotalAccesses { get; set; }
        public int? MinUniqueAccessors { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 25;
        public string? Search { get; set; }
        public int Skip => (Page - 1) * PageSize;
        public string SortColumn { get; set; } = "DataSubjectId";
        public bool SortDescending { get; set; } = true;
        // Advanced filters (friendly property names)
        public string? SubjectTypeFilter { get; set; }
        public (decimal? Min, decimal? Max)? UniqueAccessorCountFilter { get; set; }
    }

    /// <summary>Paginated result for DataSubject queries.</summary>
    public class DataSubjectFilterResult
    {
        public int Page { get; set; }
        public int PageSize { get; set; }
        public List<DataSubject> Records { get; set; } = new();
        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);
        public int TotalRecords { get; set; }
    }


    /// <summary>ComplianceReport data transfer object.</summary>
    public class ComplianceReport
    {
        /// <summary>Primary key</summary>
        public Guid ComplianceReportId { get; set; }
        public string FileUrl { get; set; } = string.Empty;
        public DateTime GeneratedAt { get; set; }
        public string GeneratedBy { get; set; } = string.Empty;
        public DateTime PeriodEnd { get; set; }
        public DateTime PeriodStart { get; set; }
        /// <summary>JSON report content</summary>
        public string ReportData { get; set; } = string.Empty;
        public string ReportType { get; set; } = string.Empty;
        public long TotalEvents { get; set; } = 0;
        public int UniqueSubjects { get; set; } = 0;
        public int UniqueUsers { get; set; } = 0;
    }

    /// <summary>Filter criteria for ComplianceReport queries.</summary>
    public class ComplianceReportFilter
    {
        public DateTime? GeneratedAfter { get; set; }
        public (DateTime? Start, DateTime? End)? GeneratedAtFilter { get; set; }
        public DateTime? GeneratedBefore { get; set; }
        public long? MaxTotalEvents { get; set; }
        public int? MaxUniqueSubjects { get; set; }
        public int? MaxUniqueUsers { get; set; }
        public long? MinTotalEvents { get; set; }
        public int? MinUniqueSubjects { get; set; }
        public int? MinUniqueUsers { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 25;
        public (DateTime? Start, DateTime? End)? PeriodEndFilter { get; set; }
        public (DateTime? Start, DateTime? End)? PeriodStartFilter { get; set; }
        // Advanced filters (friendly property names)
        public string? ReportTypeFilter { get; set; }
        public string? Search { get; set; }
        public int Skip => (Page - 1) * PageSize;
        public string SortColumn { get; set; } = "ComplianceReportId";
        public bool SortDescending { get; set; } = true;
        public (decimal? Min, decimal? Max)? UniqueSubjectsFilter { get; set; }
        public (decimal? Min, decimal? Max)? UniqueUsersFilter { get; set; }
    }

    /// <summary>Paginated result for ComplianceReport queries.</summary>
    public class ComplianceReportFilterResult
    {
        public int Page { get; set; }
        public int PageSize { get; set; }
        public List<ComplianceReport> Records { get; set; } = new();
        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);
        public int TotalRecords { get; set; }
    }


    /// <summary>Lookup DTO for SourceSystem dropdowns.</summary>
    public class SourceSystemLookup
    {
        public string DisplayName { get; set; } = string.Empty;
        public Guid SourceSystemId { get; set; }
    }

    /// <summary>Lookup DTO for AccessEvent dropdowns.</summary>
    public class AccessEventLookup
    {
        public Guid AccessEventId { get; set; }
        public string DisplayName { get; set; } = string.Empty;
    }

    /// <summary>Lookup DTO for DataSubject dropdowns.</summary>
    public class DataSubjectLookup
    {
        public Guid DataSubjectId { get; set; }
        public string DisplayName { get; set; } = string.Empty;
    }

    /// <summary>Lookup DTO for ComplianceReport dropdowns.</summary>
    public class ComplianceReportLookup
    {
        public Guid ComplianceReportId { get; set; }
        public string DisplayName { get; set; } = string.Empty;
    }

}

#endregion
