name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      SOLUTION_FILE: CRM.sln
      PROJECT_FILE: CRM/CRM.csproj
      TEST_ENDPOINT: /api/Data/GetVersionInfo
      POSSIBLE_PORTS: "5201 7048 15497"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # --- NEW: Snapshot repo before any restore/build/publish ---
    - name: Create repository snapshot (pre-build)
      shell: pwsh
      run: |
        $zip = Join-Path $env:RUNNER_TEMP "repo_snapshot_${{ github.run_id }}.zip"
        # Zip the working tree "as is" right after checkout
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\*" -DestinationPath $zip -Force
        "REPO_ZIP=$zip" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Upload repository snapshot (once)
      if: ${{ matrix.configuration == 'Debug' }}
      uses: actions/upload-artifact@v4
      with:
        name: RepoSnapshot
        path: ${{ env.REPO_ZIP }}
        if-no-files-found: error
    # -----------------------------------------------------------

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build solution (${{ matrix.configuration }})
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish project (${{ matrix.configuration }})
      run: dotnet publish ${{ env.PROJECT_FILE }} --configuration ${{ matrix.configuration }} --no-build --output ./publish/${{ matrix.configuration }}

    - name: Upload published artifact (${{ matrix.configuration }})
      uses: actions/upload-artifact@v4
      with:
        name: WebApp-${{ matrix.configuration }}
        path: ./publish/${{ matrix.configuration }}
        if-no-files-found: error
